### PR TITLE
fix merge pom's conflict on release finish using the option useSnapshotInRelease

### PR DESCRIPTION
**Pull request by hfatela**
fixes the issue #122 

I hit the same problem. I dig into the code and apply the same solution the old gitflow did. The only way to solve this is to set the version of the release into the develop branch before the merge and later revert this change back.

### CODE REVIEW

**Comment by aleksandr-m** [comment]
@jjlharrison Have you tested this solution? Does it work for you?

@hfatela Can you fix conflicts.

**Comment by hfatela** [comment]
I can, but only by the end of the day or tomorrow morning.

We are using this in my company since I upload the change in a private
build with no issues. A second test in a different environment  would be
good.

Regards

**Comment by pipwilson** [comment]
@hfatela At my workplace we have been using your change in production for a couple of months with no issue. Getting this merged would allow us to stop using our fork :)

**Comment by aleksandr-m** [comment]
@hfatela Thanks.

**Comment by aleksandr-m** [comment]
@pipwilson @hfatela `1.11.0` is out.

**Pull request merged**
