### PR TITLE
Make useSnapshotIn* available from CLI

### PR DESCRIPTION
**Pull request by riksmith**
I tried to use the new useSnapshotInHotfix in hotfix feature (which is very useful!) from the CLI. 
It did not work however because I guess the absence of "property" makes it unavailable on the CLI.

### CODE REVIEW

**Comment by aleksandr-m** [comment]
Why not to put it in your pom? Setting it from the command line can lead to errors if someone forgets to put it in the finish goal.

**Comment by riksmith** [comment]
We have all this config in our CI server so everything is in one place. I don't want to also put some stuff in our pom's when it is not needed. We never do these cli calls by hand.

**Comment by aleksandr-m** [comment]
What happens if you change ci server or get another one. Putting configuration to pom is totally ok and have some benefits as well (version control, not depending on exact ci server, etc.). 

> We never do these cli calls by hand.

But others do.

**Comment by riksmith** [comment]
We can ofcourse debate whether what we do is the smartest thing to do and if it would be better to put stuff in your pom. 

But is it really worth it to force users to use this plugin in a certain way? To me it seems such a small change without any real long term development burdain to just give the user the option to use it as he sees fit. It's not that I am removing the option to put it in the POM here (I am not aware of that anyway).

And after all: if you forget to include a CLI argument because you want do to everything by hand that's the users problem, not yours!

**Comment by aferreira82** [comment]
Just to add to this discussion, we are the same issue, we use the plugin in jenkins so there is no risk of messing this up, but since we have more than 300 projects, changing poms to deal with this issue is a problem for us.

**Comment by hfatela** [comment]
any decision? this is very important for us since we use this plugin in Jenkins and changing poms of hundred of projects is not an option for us.

**Pull request closed without merging**
