### PR TITLE
Added mergeStrategy to ease batch mode operations

### PR DESCRIPTION
**Pull request by albestia**
In order to ease batch mode operations, I've added mergeStrategy option to be one of https://git-scm.com/docs/git-merge#_merge_strategies.

### CODE REVIEW

**Comment by albestia** [comment]
Please, consider this as a proposal to verify the idea. There are some pending tasks:
* apply to all merges or specialize parameter to clarify it only refers to backMerge to develop
* Documentation update

**Comment by aleksandr-m** [comment]
Any real life use-case why do you need this? Also are you mixing up strategies with strategy options?

**Comment by albestia** [comment]
In our case for example, we create **release** branch with SNAPSHOTs, and we stabilize on **release**, while some members of the team keep on going with new features on **develop**.
From time to time, we face conflicts while merging back some changes on `pom.xml` and what we decided is that **develop** branch is the one that has the best code; so we are using this approach with `ours` as _mergeStrategy_.

**Comment by albestia** [comment]
@aleksandr-m , any news on that merge? Is there any blocking stuff that I can help you with? Thanks in advance.

**Comment by aleksandr-m** [comment]
Git merge strategies are a bit confusing, strategies vs options, naming, etc. Adding it as plain string parameter to the plugin will make it more confusing. Also it seems that benefits of the plugin regarding version changes will be lost in that way.

Why don't you fix conflicts before finishing release? It can be done for example with another merge or with cherry picking.

Btw there is no `theirs` merge strategy.

**Pull request closed without merging**
