### PR TITLE
Update pom.xml and drop beta/alpha dependencies

### PR DESCRIPTION
**Pull request by DRoppelt**
#364

Everything works just fine, I did execute `mvn verify -Prun-its` and nothing had to be adjusted.

### CODE REVIEW

**Comment by aleksandr-m** [comment]
@DRoppelt Upgrading dependencies requires java 8 and plugin uses java 7 currently. Maybe you can try to update only one dependency?

P.S. I've tried to update all dependencies and java version couple of month ago, but there was some tests failures and I haven't figured why, just yet.

**Comment by DRoppelt** [comment]
Oh I haven't considered the java7 compatibility. Yea I'll try to find out which one it is that causes it to break with 7

**Comment by DRoppelt** [comment]
@aleksandr-m Ok it was plexus-utils. 

```
java.lang.UnsupportedClassVersionError: org/codehaus/plexus/util/cli/CommandLineException : Unsupported major.minor version 52.0
```

It took a bit to find a jdk7 to verify it on my side but found a distribution here: https://www.azul.com/downloads/?version=java-7-lts&os=windows&package=jdk

**Comment by DRoppelt** [comment]
@aleksandr-m I see you linked the ticket to #369

Just so you know, the current state of this PR is compatible with java 7.

If you do chose to pull up the required version to java 8, I am happy to help. e.g. junit4->5 migration

**Comment by aleksandr-m** [comment]
@DRoppelt Yes, for this PR all tests are green! I'll probably check it manually also, cause there was a case when upgrading plexus cli to some version failed to find mvn/git executables, but all tests where fine.
I haven't decided yet when to move to java 8. The ticket is there to show intent. :) And of course I'll appreciate any help. 👍

**Pull request merged**
