### PR TITLE
Release/add check for remote branches

### PR DESCRIPTION
**Pull request by chilber**
Hey Alex,
this is a suggestion for the option of multiple release branches.
This is necessary if you cannot use support branches. In our case we have to permanently develop for 3 different versions in parallel. We have tested the solution with multiple cases and we are very fine with it and we think it will work for many other users of the plug-in, as we see in the many requests for this feature. 

When using and testing the whole workflow, we came around to see that you have a few checks implemented, a.g. to look for an existing release branch like on the release-start part. In this check you only look if a local release branch exists. If you have a CI Pipeline where you clone the repro before applying the release start, we only have a remote release branch. In your original, this leads to an unrecognized release branch when you check if a release branch exists on release-start and a not found release branch name in release-finish. 

I think our workaround and checks for the remote branches could also be helpful for other people who use stateless CI/CD pipelines.

And yes, I don't like to work on multiple release branches myself. But this is often a situation we cannot change in our role as developer. 
Cheers
Carsten

### CODE REVIEW

**Comment by aleksandr-m** [comment]
@chilber Seems there is some mix of two separate features in one PR. Please create separate PR-s for each one.

**Comment by aleksandr-m** [comment]
@chilber Ping.

**Comment by chilber** [comment]
Hi Alex, 
thanks for the ping, i'm on it.
Carsten

**Comment by chilber** [comment]
I will close this PR and add 2 PRs for the different purposes.

**Comment by sparmboy** [comment]
@ghost Could you supply the PRs you raised?

**Pull request closed without merging**
