### PR TITLE
Adds parameter "branchName" on the release-start goal

### PR DESCRIPTION
**Pull request by emmanuel-coquelin**
Issue #65 : 
Adds a parameter "branchName" on the release-start goal to specify the name of the branch to create (prefixed by the releasePrefix value).

This superseeds the "sameBranchName" parameter.

### CODE REVIEW

**Comment by manderson23** [comment]
Is this PR ever going to be merged? I'm likely to have this exact use case soon.

**Comment by aleksandr-m** [comment]
@manderson23 Which issue exactly? Can you elaborate?

**Comment by manderson23** [comment]
This PR to add the branch name parameter. It's been open for 2 years
without being merged or rejected. I wondered if it would get merged as it
would help with the workflow I need to follow.

**Comment by aleksandr-m** [comment]
@manderson23 Can you describe your workflow? Why do you need this?

**Comment by manderson23** [comment]
Release start creating a long running branch named release/1.0 where 1.0.0
and all subsequent 1.0.x releases would be made. Unlike regular usage the
branch is never merged to master.

**Comment by aleksandr-m** [comment]
@manderson23 It is a `support` branch. I don't think this PR will give you what you want.

**Comment by manderson23** [comment]
I'm pretty sure I investigated support branches and there were issues there
too that meant it didn't quite work. I've got some scripting that meets my
needs so it isn't a must have. Thanks for the feedback though.

**Pull request closed without merging**
