### PR TITLE
Add nonInteractive parameter to use hotfix-finish in a Pipeline

### PR DESCRIPTION
**Pull request by joan-miralles**
I've added a nonInteractive parameter in the hotfix-finish goal to integrate hotfix-finish in a Jenkins Pipeline.

Usage:
 mvn gitflow:hotfix-finish -DnonInteractive=true

Default value: false

### CODE REVIEW

**Comment by aleksandr-m** [comment]
What happens if there is more than one hotfix branch? Maybe it is better to add parameter which takes branch name and use it if non-interactive mode is set.

There is already a [non-interactive option in Maven](https://github.com/aleksandr-m/gitflow-maven-plugin#non-interactive-release) itself. See [here](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/8b99bc4a7c35cbad221cbea649635874e60daed6/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseStartMojo.java#L270) how to check if it is set.

Be aware that currently there is some merging issue in hotfix-finish #19.

**Comment by joan-miralles** [comment]
I've done the changes you propose me about new branchName parameter to use hotfix-finish in non-interactive mode.

Also, I've fixed the process "merge branch hotfix to develop" because every hotfix branch is merged, you increment development version (and I think it's not correct, but maybe I'm wrong) :-)

**Comment by akoita** [comment]
In the implementation of the "hotfix-finish" in non-interactive mode, why not make the parameter "hotfixVersion" facultative when there is only one hotfix branch?

**Comment by joan-miralles** [comment]
I've launched a new Pull Request to fix hotfix-finish goal when you use it as a Jenkins Pipeline

**Pull request closed without merging**
