### PR TITLE
Allow to update a property in addition to version with the generated version on release

### LINKED ISSUE #151: Support using ${revision} as the project version
As of version 3.5, maven supports using the ${revision} placeholder as the version of your project. This is useful in a multi-module project where I want to have a consistent version between all of the modules in the project and have some dependency management for the modules' versions.

Currently this gitflow plugin does not work with this approach - it is unable to parse the version from the pom when starting a release.

I can use the maven flatten plugin to flatten the pom before starting a release. This provides the release plugin with a proper version number and it can start the release, but it is not able to update the "revision" property in the pom to match the release version.

Is there any way to update the gitflow plugin to support this approach?

### PR DESCRIPTION
**Pull request by lukelalo**
This development allows to define a property to be updated when version tags are changed.

It works with the `versions-maven-plugin` and the `tycho-versions-plugin` as well.

Fix #151 

Regards
Pablo García

### CODE REVIEW

**Comment by limkinZero** [comment]
Hi @aleksandr-m 

Please, merge this feature.

**Comment by aleksandr-m** [comment]
Definitely nice to have feature, but this PR doesn't resolve #151. The release-start goal fails with `Unable to parse the version string: "${revision}"` error. This is happening because version is read from the pom.xml file.

**Comment by lukelalo** [comment]
Mmm I'll check it.
Regards

**Comment by lukelalo** [comment]
Hi @aleksandr-m, 

I've updated the IT test as our goal is to update the property to have it on children modules. I know it isn't exactly what was requested on #151, but combined with flatten maven plugin it should work.

What do you think?

Regards
Pablo García

**Comment by aleksandr-m** [comment]
@lukelalo Do you want to allow to update arbitrary property or can we narrow it to `revision` only?

Currently using flatten plugin and `-DpropertyUpdate=revision` the version will be still updated.

**Comment by lukelalo** [comment]
Hi @aleksandr-m 

What I want is to keep sync'd version on `revision` (or other) property when gitflow maven plugin updates the version number on develop, master and release branches. I'm not sure how could I achieve this with flatten plugin currently.

Regards
Pablo García

**Comment by lukelalo** [comment]
Great! Thanks! 👍

**Comment by aleksandr-m** [comment]
I've made some adjustments so #151 is also resolved.

@lukelalo Thanks for contributing.

**Pull request merged**
