### PR TITLE
added the ability to set version in non interactive mode

### PR DESCRIPTION
**Pull request by msavitskiy**

### CODE REVIEW

**Comment by aleksandr-m** [comment]
Thanks!

**Comment by msavitskiy** [comment]
Hi, @aleksandr-m when you plan to release 1.3.1 version?

**Comment by aleksandr-m** [comment]
@msavitskiy ~next week.

**Comment by msavitskiy** [comment]
@aleksandr-m it is great!

**Comment by aleksandr-m** [comment]
@msavitskiy 1.3.1 is released.

**Comment by msavitskiy** [comment]
@aleksandr-m nice!

**Pull request merged**
